FROM rust:alpine AS builder
ARG APP=xkcdbot-rs

WORKDIR /usr/src/${APP}
COPY . .
RUN apk add alpine-sdk libressl-dev
RUN cargo build --release

FROM alpine 
ARG APP=xkcdbot-rs
RUN apk add ca-certificates openssl
COPY --from=builder /usr/src/${APP}/target/release/${APP} /usr/local/bin/${APP}
CMD ["xkcdbot-rs"]